
site_name: SparkX u-blox ZED-F9P NEO-D9S Combo Breakout (SPX-20167) Product Manual
site_description: A hookup guide for the SparkX u-blox ZED-F9P NEO-D9S Combo Breakout (SPX-20167)
site_url: https://sparkfunx.github.io/u-blox_ZED-F9P_NEO-D9S_Combo_Breakout

edit_uri: edit/main/docs/

theme:
  name: material
  logo: img/sfe_logo_sm.png
  palette:
    primary: grey
    accent: red
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.tabs    

  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

plugins:
  - search
  - monorepo

repo_url: https://github.com/sparkfunX/u-blox_ZED-F9P_NEO-D9S_Combo_Breakout
repo_name: sparkfunX/u-blox_ZED-F9P_NEO-D9S_Combo_Breakout

copyright: Copyright 2022 SparkFun Electronics (6333 Dry Creek Parkway, Niwot, Colorado 80503)

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - tables
  - admonition
  - md_in_html
  - attr_list

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/sparkfun
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/sparkfun
    - icon: fontawesome/brands/github
      link: https://www.github.com/sparkfun
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/SparkFun
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sparkfun
  
nav:
  - SparkX u-blox ZED-F9P NEO-D9S Combo Breakout: index.md
  - Product Manual:
    - Getting Started: getting_started.md
    - Hardware Overview: hardware_overview.md
    - Hardware Assembly: hardware_assembly.md
    - Software Overview: software_overview.md
  - Product Resources:
    - Board Files: board_files.md
    - Resources: resources.md
    - Troubleshooting Tips: troubleshooting_tips.md
  - Contribution/Issues:
    - Issues: file_issue.md
    - Contribute: contribute.md